services:
  backend:
    build:
      context: ./backend
    container_name: e-library-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: e-library-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
