from .models import Book


BOOKS: list[Book] = [
    Book(
        id=1,
        title="Мастер и Маргарита",
        authors=["Михаил Булгаков"],
        description="Роман о любви, свободе, творчестве и сложном выборе человека в обществе.",
        publisher="Азбука",
        year=1967,
        pages=480,
        isbn="978-5-389-01662-0",
        language="Русский",
        category="Классика",
        cover_color="#7c2d12",
        available_copies=4,
        rating=4.9,
        read_url="https://openlibrary.org/",
    ),
    Book(
        id=2,
        title="Преступление и наказание",
        authors=["Фёдор Достоевский"],
        description="Психологический роман о нравственном конфликте, ответственности и раскаянии.",
        publisher="Эксмо",
        year=1866,
        pages=672,
        isbn="978-5-04-112802-5",
        language="Русский",
        category="Классика",
        cover_color="#1f2937",
        available_copies=2,
        rating=4.8,
        read_url="https://openlibrary.org/",
    ),
    Book(
        id=3,
        title="Clean Code",
        authors=["Robert C. Martin"],
        description="Практическое руководство по написанию понятного, поддерживаемого и качественного кода.",
        publisher="Prentice Hall",
        year=2008,
        pages=464,
        isbn="978-0132350884",
        language="English",
        category="Программирование",
        cover_color="#2563eb",
        available_copies=6,
        rating=4.7,
        read_url="https://openlibrary.org/",
    ),
    Book(
        id=4,
        title="Designing Data-Intensive Applications",
        authors=["Martin Kleppmann"],
        description="Книга объясняет архитектуру современных систем данных, репликацию, транзакции и потоковую обработку.",
        publisher="O'Reilly Media",
        year=2017,
        pages=616,
        isbn="978-1449373320",
        language="English",
        category="Базы данных",
        cover_color="#0f766e",
        available_copies=3,
        rating=4.9,
        read_url="https://openlibrary.org/",
    ),
    Book(
        id=5,
        title="Алиса в Стране чудес",
        authors=["Льюис Кэрролл"],
        description="Сказочная история о девочке Алисе, попавшей в необычный мир логики и фантазии.",
        publisher="Махаон",
        year=1865,
        pages=192,
        isbn="978-5-389-10769-4",
        language="Русский",
        category="Детская литература",
        cover_color="#be185d",
        available_copies=8,
        rating=4.6,
        read_url="https://openlibrary.org/",
    ),
    Book(
        id=6,
        title="The Pragmatic Programmer",
        authors=["Andrew Hunt", "David Thomas"],
        description="Советы для разработчиков о мышлении, проектировании, отладке и профессиональном росте.",
        publisher="Addison-Wesley",
        year=2019,
        pages=352,
        isbn="978-0135957059",
        language="English",
        category="Программирование",
        cover_color="#9333ea",
        available_copies=5,
        rating=4.8,
        read_url="https://openlibrary.org/",
    ),
    Book(
        id=7,
        title="Война и мир",
        authors=["Лев Толстой"],
        description="Эпический роман о российском обществе, семье, войне и исторических переменах.",
        publisher="АСТ",
        year=1869,
        pages=1225,
        isbn="978-5-17-090630-3",
        language="Русский",
        category="Классика",
        cover_color="#854d0e",
        available_copies=1,
        rating=4.7,
        read_url="https://openlibrary.org/",
    ),
    Book(
        id=8,
        title="Introduction to Algorithms",
        authors=["Thomas H. Cormen", "Charles E. Leiserson", "Ronald L. Rivest", "Clifford Stein"],
        description="Фундаментальный учебник по алгоритмам, структурам данных и анализу сложности.",
        publisher="MIT Press",
        year=2022,
        pages=1312,
        isbn="978-0262046305",
        language="English",
        category="Алгоритмы",
        cover_color="#334155",
        available_copies=2,
        rating=4.8,
        read_url="https://openlibrary.org/",
    ),
]
